#cloud-config
apt_update: true
apt_upgrade: true
packages:
  - zsh
  - wget
  - curl
  - python3
  - python3-pip
  - python3-dev
  - vim-nox
  - git
  - zip
  - unzip
  - build-essential
  - cmake
  - sudo
users:
  - name: jdkula
    gecos: Jonathan Kula
    primary_group: jdkula
    groups: sudo
    shell: /usr/bin/zsh
runcmd:
  - sudo -i -u jdkula wget "https://raw.githubusercontent.com/jdkula/dotfiles/master/setup.sh" -O \$HOME/setup.sh
  - sudo -i -u jdkula chmod +x \$HOME/setup.sh
  - sudo -i -u jdkula \$HOME/setup.sh
  - sudo -i -u jdkula mkdir \$HOME/.ssh
  - sudo -i -u jdkula sh -c "curl https://github.com/jdkula.keys > \$HOME/.ssh/authorized_keys"
